Js homework two
Tosheva95/HTML-homework pull request #13
Opened 2020-11-23 14:18 UTC by Tosheva95

2020-11-23 15:03 UTC, dpeshevski requested changes

2020-11-23 15:03 UTC, dpeshevski commented on js-homework-two/JS-homework-2/palindromes.js
> +var list = ['Македонија','анаволимилована','дај ми една чаша полна со вино','радар','кајак', 'калабалак','нели не си ти сенилен','јадење и пиење дај','слушател','фудбал','музика'];
Зошто `var`? Кога го користивме за декларирање на променлива?

2020-11-23 15:03 UTC, dpeshevski commented on js-homework-two/JS-homework-2/palindromes.js
> +		let palindromes = [];
лоша идентација.

2020-11-23 15:03 UTC, dpeshevski commented on js-homework-two/JS-homework-2/palindromes.js
> +		let palindromes = [];
зошто `let`?

2020-11-23 15:03 UTC, dpeshevski commented on js-homework-two/JS-homework-2/palindromes.js
> +				let pal = list[i].split('').reverse().join('');
пак лоша идентација... кодот е многу на десно, не е добро уреден.

2020-11-23 15:03 UTC, dpeshevski commented on js-homework-two/JS-homework-2/palindromes.js
> +				let pal = list[i].split('').reverse().join('');
што ќе се случи ако испратиш во низата `list` и број? 

`list = ['Македонија', 5225, 1111, 84548458, 112232211, 'анаволимилована','дај ми една чаша полна со вино','радар','кајак', 'калабалак','нели не си ти сенилен','јадење и пиење дај','слушател','фудбал','музика'];`

2020-11-23 15:03 UTC, dpeshevski commented on js-homework-two/JS-homework-2/palindromes.js
> +    console.log(palindromes);
Зошто тука ги печатиш? Тука треба само да ги враќаш.

`return palindromes;`

2020-11-23 15:03 UTC, dpeshevski commented on js-homework-two/JS-homework-2/palindromes.js
> +        if (pal.replaceAll(' ', '') === list[i].replaceAll(' ', '')) {
што прави овој код `.replaceAll(' ', '')`?

2020-11-23 15:03 UTC, dpeshevski commented on js-homework-two/JS-homework-2/palindromes.js
> +				let pal = list[i].split('').reverse().join('');
што прави `list[i].split('').reverse()`? 

што прави `join('')`?

2020-11-23 15:03 UTC, dpeshevski commented on js-homework-two/JS-homework-2/palindromes.js
> +findPalindrome(list);
тука треба да го испечатиш резултатот.

2020-11-23 15:03 UTC, dpeshevski commented on js-homework-two/JS-homework-2/even-lenght-words.js
> +var str1 = str.split(' ');
што е `str` и `str1`?
зошто се декларирани со користење на `var`?

2020-11-23 15:03 UTC, dpeshevski commented on js-homework-two/JS-homework-2/even-lenght-words.js
> +	let arr = []
ти недостасува `;`

2020-11-23 15:03 UTC, dpeshevski commented on js-homework-two/JS-homework-2/even-lenght-words.js
> +	let arr = []
што означува `arr`?

2020-11-23 15:03 UTC, dpeshevski commented on js-homework-two/JS-homework-2/even-lenght-words.js
> +		arr.push(array[i]);
изгледа многу грдо со лоша идентација.....

2020-11-23 15:03 UTC, dpeshevski commented on js-homework-two/JS-homework-2/even-lenght-words.js
> +		if (array[i].length % 2 === 0) {
што прави `array[i].length % 2 === 0`

2020-11-23 15:03 UTC, dpeshevski commented on js-homework-two/JS-homework-2/even-lenght-words.js
> +function myFunction(array) {
што означува `myFunction`?????????

2020-11-23 15:03 UTC, dpeshevski commented on js-homework-two/JS-homework-2/even-lenght-words.js
> +	return arr
пак ти недостасува `;`

2020-11-23 15:03 UTC, dpeshevski commented on js-homework-two/JS-homework-2/even-lenght-words.js
> +let occurencies = new Object();
што прави ова?

2020-11-23 15:03 UTC, dpeshevski commented on js-homework-two/JS-homework-2/even-lenght-words.js
> +	if(occurencies[evenStrings[i]] != null) {
што проверува??

2020-11-23 15:03 UTC, dpeshevski commented on js-homework-two/JS-homework-2/even-lenght-words.js
> +		occurencies[evenStrings[i]] += 1;
што прави оваа линија?

2020-11-23 15:03 UTC, dpeshevski commented on js-homework-two/JS-homework-2/even-lenght-words.js
> +}
дали тоа целиот `for` loop е надвор од фунцијата? може да ми објасниш зошто?

2020-11-23 15:03 UTC, dpeshevski commented on js-homework-two/JS-homework-2/even-lenght-words.js
> +	for (let i = 0; i < array.length; i++) {
што прави овој for loop?

2020-11-23 15:03 UTC, dpeshevski commented on js-homework-two/JS-homework-2/even-lenght-words.js
> +for (let i = 0; i < evenStrings.length; i++) {
што прави овој for loop?

2020-11-23 15:03 UTC, dpeshevski commented on js-homework-two/JS-homework-2/palindromes.js
> +            palindromes.push(list[i]);
што прави оваа линија код?

2020-11-23 16:56 UTC, Tosheva95 commented on js-homework-two/JS-homework-2/palindromes.js
> +            palindromes.push(list[i]);
Прво ги поминува сите зборови од низата едно по едно. Со Split е разделен стрингот по зборчиња, потоа reverse за да ги преврти од назад и join сите елементи во arrey- от ги конвертира во еден String. Replace се користи за да ги фати палиндромите кои имаат space измеѓу зборовите. Во овој случај replaceAll бидејќи со replace го брише само првото празно место.

2020-11-23 16:58 UTC, Tosheva95 commented on js-homework-two/JS-homework-2/palindromes.js
> +            palindromes.push(list[i]);
и push за да ја додаде листата (list[i]) во празниот array кој е дефинират претходно

2020-11-23 16:59 UTC, Tosheva95 commented on js-homework-two/JS-homework-2/even-lenght-words.js
> +for (let i = 0; i < evenStrings.length; i++) {
Ги поминува сите зборови од низата (evenStrings) едно по едно.

2020-11-23 17:01 UTC, Tosheva95 commented on js-homework-two/JS-homework-2/even-lenght-words.js
> +	for (let i = 0; i < array.length; i++) {
Ги поминува сите зборови од листата array едно по едно за потоа со команда во if со % 2 === 0 од тие зборови да ги издвои парните зборови.

2020-11-23 17:03 UTC, Tosheva95 commented on js-homework-two/JS-homework-2/even-lenght-words.js
> +}
ја повикувам функцијата со evenStrings :)

2020-11-23 17:14 UTC, Tosheva95 commented on js-homework-two/JS-homework-2/even-lenght-words.js
> +		occurencies[evenStrings[i]] += 1;
!=null // да е различно од null или да не е еднакво на null, во случајов значи варијаблата да не е празна. Да ги испринта зборовите кои се += 1 (присутни повеќе од еден пат) и =1 кои се појавуваат само еден пат во низата.

2020-11-23 17:15 UTC, Tosheva95 commented on js-homework-two/JS-homework-2/palindromes.js
> +        if (pal.replaceAll(' ', '') === list[i].replaceAll(' ', '')) {
ги брише сите празни места.

2020-11-23 17:16 UTC, Tosheva95 commented on js-homework-two/JS-homework-2/palindromes.js
> +    console.log(palindromes);
океј :)

2020-11-23 17:21 UTC, Tosheva95 commented on js-homework-two/JS-homework-2/palindromes.js
> +				let pal = list[i].split('').reverse().join('');
доколку има броеви во split ќе користам запирка split(',') . Со Split е разделен стрингот по зборчиња, потоа reverse за да ги преврти од назад и join сите елементи во arrey- от ги конвертира во еден String.

2020-11-23 17:22 UTC, Tosheva95 commented on js-homework-two/JS-homework-2/palindromes.js
> +		let palindromes = [];
па тоа имаме учено.

2020-11-23 17:24 UTC, Tosheva95 commented on js-homework-two/JS-homework-2/palindromes.js
> +var list = ['Македонија','анаволимилована','дај ми една чаша полна со вино','радар','кајак', 'калабалак','нели не си ти сенилен','јадење и пиење дај','слушател','фудбал','музика'];
може  const да се употреби :)

2020-11-23 17:44 UTC, dpeshevski commented on js-homework-two/JS-homework-2/palindromes.js
> +		let palindromes = [];
Која е разликата помеѓу let и const? Кога се користат?

2020-11-23 17:46 UTC, Tosheva95 commented on js-homework-two/JS-homework-2/palindromes.js
> +findPalindrome(list);
ако не стои ова дека ја повикувам функцијата не дава резултат.

2020-11-23 17:48 UTC, dpeshevski commented on js-homework-two/JS-homework-2/palindromes.js
> +				let pal = list[i].split('').reverse().join('');
Можеш да го пробаш ова test case со броеви во низа ама од data type Number (исто како што го напишав погоре) и доколку имаш проблеми да ги пријавиш што ти е грешката, и да најдеш решение како можеш и број да имаш во низата.

2020-11-23 17:49 UTC, dpeshevski commented on js-homework-two/JS-homework-2/palindromes.js
> +				let pal = list[i].split('').reverse().join('');
Да ти работи функцијата и за броеви. Може?

2020-11-23 17:51 UTC, dpeshevski commented on js-homework-two/JS-homework-2/palindromes.js
> +        if (pal.replaceAll(' ', '') === list[i].replaceAll(' ', '')) {
Што означува првиот аргумент на методата, а што вториот. Те прашувам за `' ', ''`

2020-11-23 17:52 UTC, dpeshevski commented on js-homework-two/JS-homework-2/palindromes.js
> +findPalindrome(list);
Те молам види во предавањето за functions, и ќе го решиш. :)

2020-11-23 17:55 UTC, dpeshevski commented on js-homework-two/JS-homework-2/even-lenght-words.js
> +}
Ама зошто овој for е надвор? Замисли имаш уште 10 различни функции, што мислиш дека ќе се случи тогаш ако вака го пишуваме?

Треба да ти биде внатре во рамките на функцијата. Те молам размисли како ќе го вклопиш во функција, доколку заглавиш ping me.

2020-11-23 17:56 UTC, dpeshevski commented on js-homework-two/JS-homework-2/even-lenght-words.js
> +	for (let i = 0; i < array.length; i++) {
Како ќе биде ако сакаме да напишеме услов за непарен број?

2020-11-30 17:30 UTC, dpeshevski requested changes
@Tosheva95 среди ги забелешките за да можам да ти ја одобрам домашната.

2020-11-30 17:30 UTC, dpeshevski commented on js-homework-two/JS-homework-2/even-lenght-words.js
> +let occurencies = new Object();
Ова креира нова инстанца од Object.

2020-11-30 17:30 UTC, dpeshevski commented on js-homework-two/JS-homework-2/even-lenght-words.js
> +		occurencies[evenStrings[i]] += 1;
Ова доделува вредност, и при секоја интеракција се зголемува за 1 ако постои збор во реченицата.

2020-11-30 17:30 UTC, dpeshevski commented on js-homework-two/JS-homework-2/palindromes.js
> +var list = ['Македонија','анаволимилована','дај ми една чаша полна со вино','радар','кајак', 'калабалак','нели не си ти сенилен','јадење и пиење дај','слушател','фудбал','музика'];
Употреби, те молам.

2020-12-09 15:45 UTC, dpeshevski approved these changes

2020-12-09 21:02 UTC, merged