Hacker rank
Tosheva95/HTML-homework pull request #17
Opened 2020-12-09 22:32 UTC by Tosheva95

2020-12-09 22:59 UTC, dpeshevski requested changes
Има неколку грешки кои треба да се поправат, оставени се забелешки. Откако ќе ги поправиш те молам извести ме повторно да го прегледа и остави коментар дека е поправено.

2020-12-09 22:59 UTC, dpeshevski commented on hackerRank/hakerRank2/apple-and-orange.js
> +    const orangeRes= oranges.map(num => num + b).filter(num => num >= s && num <=t).length;
Барам детално објаснување на кодот од почеток до крај што прави.

2020-12-09 22:59 UTC, dpeshevski commented on hackerRank/hakerRank2/camelCase.js
> +    let count = 1;
Зошто 1?

2020-12-09 22:59 UTC, dpeshevski commented on hackerRank/hakerRank2/compare-the-triplets.js
> +
Што прави кодот од 29 до 34 линија? Објаснување во детали.

2020-12-09 22:59 UTC, dpeshevski commented on hackerRank/hakerRank2/diagonal-difference.js
> +}
Објаснување во детали на решението.

2020-12-09 22:59 UTC, dpeshevski commented on hackerRank/hakerRank2/grading-students.js
> +  var numberToRoundAt = 2;
Var???? Зоштооо?

2020-12-09 22:59 UTC, dpeshevski commented on hackerRank/hakerRank2/grading-students.js
> +  for(var i = 0; i < grades.length; i++) {
И тука зошто var?

2020-12-09 22:59 UTC, dpeshevski commented on hackerRank/hakerRank2/mini-max-sum.js
> +    for (let i = 0; i < 5; i++) {
Зошто 5?

2020-12-09 22:59 UTC, dpeshevski commented on hackerRank/hakerRank2/simple-array-sum.js
> +
Што прави ова? И не ти е целосна btw..

2020-12-09 22:59 UTC, dpeshevski commented on hackerRank/hakerRank2/strong-password.js
> +    var musthaveChars=0;
Ок Ивана, зошто користиш var?

2020-12-09 22:59 UTC, dpeshevski commented on hackerRank/hakerRank2/strong-password.js
> +
Зошто има празна линија???

2020-12-09 22:59 UTC, dpeshevski commented on hackerRank/hakerRank2/strong-password.js
> +                password.charAt(i)==")" || password.charAt(i)=="-" || password.charAt(i)=="+"){
Што прави овој else...

2020-12-09 22:59 UTC, dpeshevski commented on hackerRank/hakerRank2/strong-password.js
> +    var len= n+musthaveChars;
Var.....??

2020-12-10 22:18 UTC, Tosheva95 commented on hackerRank/hakerRank2/apple-and-orange.js
> +    const orangeRes= oranges.map(num => num + b).filter(num => num >= s && num <=t).length;
На hackerRank се дефинирани

const apples = [2, 3, -4] 
const oranges = [3, 2, 4]. 
const a = 4 ; const b = 12; const s = 7; const t = 10

Е сега со apples.map се проверува следново: на местото на num се врши проверка на елементите од const apples, односно:
4 + 2 = 6; 4 + 3 = 7; 4 - 4 = 0 // [6, 7, 0]
Со .filter се извршува проверка кој од 6, 7, 0 е >= s && <= t, односно:
6 >= 7 && 6 <= 10// false ;
7 >= 7 && 7<= 10// true;
0 >= 7 && 0<=10// false

Поради .length како output се добива бројот на елементи (паднати јаболки) кои паднале на дистанца на која се наоѓа куќата од 7 до 10.
Таков е само еден елемент, извршен со проверката 7 >= 7 && 7<= 10, поради тоа во конзола ќе добиеме 1

Истата постапка е направена и за портокалите. 

4 + 3 = 7; 4 + 2 = 6; 4 + 4 = 8 // [7, 6, 8]

7 >= 7 && 7 <= 10// true ;
6 >= 7 && 6<= 10// false;
8 >= 7 && 8<=10// true

Поради .length како output се добива бројот на елементи (паднати портокали) кои паднале на дистанца на која се наоѓа куќата од 7 до 10.
Такви се два елементи, извршени со проверките:

7 >= 7 && 7 <= 10
8 >= 7 && 8<=10

Поради тоа во конзола ќе добиеме 2.

@dpeshevski :

2020-12-10 22:31 UTC, dpeshevski commented on hackerRank/hakerRank2/apple-and-orange.js
> +    const orangeRes= oranges.map(num => num + b).filter(num => num >= s && num <=t).length;
@Tosheva95 благодарам. Сега веќе ми е јасно. 😊

2020-12-10 22:37 UTC, Tosheva95 commented on hackerRank/hakerRank2/camelCase.js
> +    let count = 1;
За зададената const s = saveChangesInTheEditor
Целиот for loop ни врши проверка при секоја голема буква да се смета дека е нов збор, односно како output да го добиеме бројот на зборови во const s. Тоа е бројот 5
Тоа се зборовите save; changes; in; the; editor

let count = 1, е со цел броењето на зборовите да започне од 1, односно 1, 2, 3, 4, 5 - output 5
Во случај ако беше let count = 0, односно 0, 1, 2, 3, 4 - како output ќе добиевме 4.

@dpeshevski

2020-12-10 22:40 UTC, dpeshevski commented on hackerRank/hakerRank2/camelCase.js
> +    let count = 1;
Во ред. А зошто започнува од 1?

2020-12-10 22:42 UTC, dpeshevski commented on hackerRank/hakerRank2/camelCase.js
> +    let count = 1;
Тоа го означува првиот збор? Така?

2020-12-10 22:44 UTC, dpeshevski commented on hackerRank/hakerRank2/camelCase.js
> +    let count = 1;
Дали има решение како да добиеме 5 иако count би започнал од 0?

2020-12-10 23:35 UTC, Tosheva95 reviewed
Korekcii

2020-12-10 23:35 UTC, Tosheva95 commented on hackerRank/hakerRank2/compare-the-triplets.js
> +
Во суштина задачата е поставена на следниов начин -> личноста која има подобар резултат добива 1 поен, ако имаат ист резултат, ниту личноста А ниту личноста Б не добиваат поен.
Според тоа,
линија 29: Ако резултатот на А е поголем од рез. на Б ...
линија 30: ... Поен добива личноста со индекс [0], односно првата личност А...
линија 31: ... else(во спротивно) Ако резултатот на А е помал од рез. на Б...
линија 32: ... Поен добива личноста со индекс [1], односно втората личност Б...
линија 33: ... Ако резултатот е еднаков, ниту личност А ниту личност Б не добиваат поен...
линија 34: ... curly bracket :D 
@dpeshevski

2020-12-10 23:35 UTC, Tosheva95 commented on hackerRank/hakerRank2/mini-max-sum.js
> +    for (let i = 0; i < 5; i++) {
Барањето на задачата е да го добиеме минималниот и максималниот збир на **4** од вкупно 5 елементи од зададената низа:
const arr = [1, 2, 3, 4, 5]

Бидејќи низата содржи 5 елементи, ставено е i < 5, за да не се изврши for loop проверката за секој елемент, туку за 4.
@dpeshevski

2020-12-10 23:48 UTC, Tosheva95 commented on hackerRank/hakerRank2/grading-students.js
> +  var numberToRoundAt = 2;
корегирано :)

2020-12-11 00:10 UTC, Tosheva95 commented on hackerRank/hakerRank2/camelCase.js
> +    let count = 1;
Ако започнува од 0, повторно добиваме 5 збора, со тоа што броењето се извршува:
0, 1, 2, 3, 4 // 5
За разлика од count = 1 кај што броењето оди
1, 2, 3, 4, 5 // 5

2020-12-11 00:15 UTC, Tosheva95 commented on hackerRank/hakerRank2/strong-password.js
> +
корегирано

2020-12-11 00:32 UTC, dpeshevski commented on hackerRank/hakerRank2/camelCase.js
> +    let count = 1;
Во ред. Дали постои решение или можност како output да биде 5 во случај ако count започнува од 0? Што мислиш?

2020-12-11 22:11 UTC, Tosheva95 commented on hackerRank/hakerRank2/simple-array-sum.js
> +
Reduce method - се користи за враќање на сите елементи од низата во единствена вкупна вредност (врз основа на тоа дали операцијата што ја задаваме, ќе биде собирање, одземање, множење, делење..)
Во случајов за дадена const ar = [1, 2, 3, 4, 10, 11], задаваме функција accumulator + current, односно **собирање** на елементите од низата од лево кон десно, еден по еден.
1 + 2 + 3 + 4 + 10 + 11 = 31
@dpeshevski

2020-12-11 22:38 UTC, Tosheva95 commented on hackerRank/hakerRank2/strong-password.js
> +                password.charAt(i)==")" || password.charAt(i)=="-" || password.charAt(i)=="+"){
На hackerrank е зададено следново во делот дека мора да постои special character:
It contains at least one special character. The special characters are: **!@#$%^&*()-+**

Секој посебно од special карактерите се вметнати во овој else меѓусебно поврзани со **или ||**.
Врз основа на тоа, при впишувањето на барем еден од нив во полето за пасворд, ќе биде исполнет условот за постоење на барем еден special карактер, и ќе се продолжи кон следната проверка..

@dpeshevski

2020-12-11 23:23 UTC, Tosheva95 commented on hackerRank/hakerRank2/camelCase.js
> +    let count = 1;
Постои ако првата буква s, од зададениот стринг (const s = saveChangesInTheEditor) ја конвертираме во голема S (toUpperCase).
Во тој случај ако count започнува од 0, ќе даде 5, затоа што и првиот збор ќе почнува на голема буква. 
Друго решение во моментов не ми текнува .. 

@dpeshevski

2020-12-11 23:36 UTC, dpeshevski approved these changes

2020-12-11 23:36 UTC, dpeshevski commented on hackerRank/hakerRank2/strong-password.js
> +    }
од 52 до 63, не е исто? зарем не може во еден if да биде напишано? што мислиш? може, не може?

2021-01-26 16:38 UTC, merged